public_gsheets_url = "https://docs.google.com/spreadsheets/d/1N027WgDwc2yPGI7m69eBo23yOPhSs55JudVgejcpDbQ/edit?usp=sharing"

[gsheets]
apps_script_url = "https://script.google.com/macros/s/AKfycbxForZ6swV7cyA6Jhs1_P-GgKBtubRpmra8WJsrj20UBgZ8pM7vhCQVZPwRlLrPTspt/exec"